# Base configuration for tms tests.

# general options that are not "per product".
tms smart setup options:

  error if skipped: true

  servers:
    local:
      enabled: true

    tms:
      enabled: true

    community:
      enabled: false

  git:
    # Location where to find git.exe. If not specified, smart setup will search for the first git.exe available in the OS PATH.
    #git location: c:\git\git.exe

    # Here you can specify extra parameters for the git clone call. If not specified, smart setup will do a plain clone.
    #clone command: clone

    # Command for git pull
    #pull command: pull

    # Command for a shallow clone that will be used to get a single file.
    #shallow clone command: clone --depth 1 --filter=blob:none --sparse

  svn:
    # Location where to find svn.exe. If not specified, smart setup will search for the first git.exe available in the OS PATH.
    #svn location: C:\fpc\fpcbootstrap\svn\bin\svn.exe

    # Here you can specify extra parameters for the svn checkout call. If not specified, smart setup will do a plain checkout.
    #checkout command: checkout

    # Command for svn update
    #update command: update

    # Command for svn export
    #export command: export


configuration for all products:
  options:
    # can be info, messages or errors
    verbosity: info
    skip register: true
  delphi versions:
    - delphi12
    #- delphi13

  # specify the platforms you want to be built/installed.
  # if this option is omitted, it will try to build for all platforms supported by the IDE.
  # smart setup will anyway avoid building to a platform if it's not supported or property installed/configured.
  platforms:
    - win32intel
    #- win64intel
    #- macos32intel
    #- macos64intel
    #- macos64arm
    #- iossimulator
    #- iosdevice32
    #- iosdevice64
    #- android32
    #- android64
    #- linux64
    #- iossimulator64arm
    #- win64xintel

  compilation options:
    debug dcus: false

  advanced options:
    keep parallel folders: true
 
  compiler paths:
    #lazarus: C:\fpc\lazarus
    #delphi12: C:\Program Files (x86)\Embarcadero\Studio\23.0

