# Sample workflow for building and deploying a xmldocer site to AWS S3
name: Deploy documentation to AWS S3

on:
  # Runs on pushes targeting the default branch
  #push:
  #  branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  xmldocer:
    uses: ./.github/workflows/xmldocer-build-pages.yml

  # Build job
  build:
    runs-on: ubuntu-latest
    needs: xmldocer

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload documentation files 
        run: aws s3 sync /doc/_output/_site s3://tms-site-doc/smartsetup

      - name: Invalidate CDN
        run: aws cloudfront create-invalidation --distribution-id E28KJG21XS16K3 --paths "/smartsetup*"